import type { Metadata } from "next";
import LeftSidebar from "@/components/LeftSidebar";
import Image from "next/image";
import RightSidebar from "@/components/RightSidebar";
import { Toaster } from "@/components/ui/toaster";
import PodcastPlayer from "@/components/PodcastPlayer";

export const metadata: Metadata = {
  title: "Pody",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex flex-col">
        <main className="relative flex bg-black-3">
            <LeftSidebar/>

            <section className=" flex-1 flex-col px-4 sm:px-14">
              <div className=" mx-auto flex w-full max-w-5xl 
              flex-col px-4 max-sm-px-4">
                <div className="flex h-16 items-center justify-between 
                md:hidden">
                  {/* <Image src="/icons/logo.svg" width={30} height={30}
                  alt="manu icon"/> */}
                  {/* MobileNav */}
                </div>
                <div className="flex flex-col md:pb-14">
                  <Toaster/>
                  {children}
                </div>
              </div>
            </section>

            <RightSidebar/>
        </main>
        <PodcastPlayer/>
    </div>
  );
}

